title: "Fitbit to Apple Health Sync App"
description: "Sync your Fitbit data with Apple Health seamlessly."
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
baseurl: ""
url: "https://stelath.github.io/fitbit-sync"

# Navigation Links
nav_links:
  - name: "Home"
    link: "/"
  - name: "Terms of Service"
    link: "/terms-of-service"
  - name: "Privacy Policy"
    link: "/privacy-policy"

# Exclude files from the build
exclude:
  - README.md
  - LICENSE